trigger: none

resources:
  pipelines:
    - pipeline: self-hosted-agent-pool
      source: self-hosted-agent-pool
      trigger:
        branches:
          include:
            - '*'

stages:
- stage: ExecuteScript
  jobs:
  - job: ExecuteScriptJob
    steps:
    - script: ./deploy-msql.sh
      displayName: 'Execute Bash Script For MySQL'
