trigger:
- main  # Specify the branch to trigger the pipeline

pool:
  name: 'self-hosted-agent-pool'  #The manually created self hosted agent pool

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script: echo 'Building your application...'
      displayName: 'Build Application'

- stage: Deploy
  jobs:
  - job: DeployJob
    steps:
    - script: echo 'Deploying to Kubernetes...'
      displayName: 'Deploy to AKS'

