trigger: none

pool:
  name: 'self-hosted-agent-pool'

resources:
  pipelines:
    - pipeline: K8s-nginx-pipeline
      source: K8s-nginx-pipeline
      trigger: true

stages:
- stage: ExecuteScript
  jobs:
  - job: ExecuteScriptJob
    steps:
    - script: |
        echo "Current working directory: $(pwd)"
        /home/mnikolov/K8s-deployment-ado/ADO-pipelines/msql/deploym.sh
      displayName: 'Execute Bash Script For MySQL'
