apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
  namespace: az-pl
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Welcome Matey!</title>
    </head>
    <body>
        <h1>This webpage is ran on Nginx webserver! :)</h1>
    </body>
    </html>
