trigger:
- none

pool:
  name: 'self-hosted-agent-pool'

stages:
- stage: RunScripts
  jobs:
  - job: RunScriptsJob
    steps:
    - script: |
        echo "Starting the application..."
        /home/mnikolov/K8s-deployment-ado/ADO-pipelines/start-app.sh
      displayName: 'Run start-app.sh'

    - script: |
        echo "Running run.sh..."
        /home/mnikolov/K8s-deployment-ado/ADO-pipelines/run.sh
      displayName: 'Run run.sh'

    - script: |
        echo "Deploying nginx..."
        /home/mnikolov/K8s-deployment-ado/ADO-pipelines/nginx/deploy-nginx.sh
      displayName: 'Run deploy-nginx.sh'

    - script: |
        echo "Deploying MySQL..."
        /home/mnikolov/K8s-deployment-ado/ADO-pipelines/msql/deploym.sh
      displayName: 'Run deploym.sh'

    - script: |
        echo "Running cleanup..."
        /home/mnikolov/K8s-deployment-ado/ADO-pipelines/cleanup.sh
      displayName: 'Run cleanup.sh'

- stage: PublishArtifacts
  dependsOn: RunScripts
  jobs:
  - job: PublishArtifactsJob
    steps:
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '/home/mnikolov/K8s-deployment-ado/ADO-pipelines/log'
        ArtifactName: 'logs'
        publishLocation: 'Container'
      displayName: 'Publish Log Artifacts'
