trigger: none

pool:
  name: 'self-hosted-agent-pool'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script: echo 'Building your application...'
      displayName: 'Build Application'

- stage: Deploy
  jobs:
  - job: DeployJob
    steps:
    - script: echo 'Deploying to Kubernetes...'
      displayName: 'Deploy to AKS'

- stage: ExecuteScript
  jobs:
  - job: ExecuteScriptJob
    steps:
    - script: /home/mnikolov/ADO-pipelines/ADO-pipelines/run.sh
      displayName: 'Execute Bash Script'
