trigger:
- none

pool:
  name: 'self-hosted-agent-pool'

stages:
- stage: Verify
  jobs:
  - job: VerifyJob
    steps:
    - script: |
        echo "TF_BUILD = $TF_BUILD"
        printenv | grep TF_BUILD
      displayName: 'Verify TF_BUILD Environment Variable'

- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script: echo 'Building your application...'
      displayName: 'Build Application'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'build'
        publishLocation: 'Container'
      displayName: 'Publish Build Artifacts'

- stage: Deploy
  jobs:
  - job: DeployJob
    steps:
    - script: echo 'Deploying to Kubernetes...'
      displayName: 'Deploy to AKS'

- stage: ExecuteScript
  jobs:
  - job: ExecuteScriptJob
    steps:
    - script: /home/mnikolov/K8s-deployment-ado/ADO-pipelines/start-app.sh
      displayName: 'Execute Bash Script'
