apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <h1>Welcome</h1>
      <p>This is my custom HTML content.</p>
    </html>
